# Generated by Django 6.1.1 on 2026-09-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='education_score',
            field=models.FloatField(blank=True, help_text='AI-generated education matching score.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience_score',
            field=models.FloatField(blank=True, help_text='AI-generated experience matching score.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='recommendation',
            field=models.CharField(blank=True, help_text='AI-generated recruitment recommendation.', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='skills_score',
            field=models.FloatField(blank=True, help_text='AI-generated skills similarity score.', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='match_score',
            field=models.FloatField(blank=True, help_text='Overall AI-generated candidate-job matching score.', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('AI_SCREENING', 'AI Screening'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
    ]
